# Generated by Django 3.0.4 on 2020-03-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('Gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transcript')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_transcripts', to='main.Gene')),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_transcripts', to='main.Panel')),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='genes',
            field=models.ManyToManyField(related_name='Panels', through='main.SelectedTranscript', to='main.Gene'),
        ),
    ]
