# Generated by Django 3.0.4 on 2020-03-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedtranscript',
            old_name='amount',
            new_name='transcript',
        ),
    ]
