# Generated by Django 3.0.4 on 2020-03-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200311_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PanelGene', to='main.Gene')),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PanelGene', to='main.Panel')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrefferedTranscript', to='main.Transcript')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedTranscript',
        ),
        migrations.AlterField(
            model_name='panel',
            name='genes',
            field=models.ManyToManyField(related_name='Panels', through='main.PanelGene', to='main.Gene'),
        ),
    ]
