# Generated by Django 3.0.4 on 2020-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200311_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
