# Generated by Django 3.0.4 on 2020-03-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200311_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelgene',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PanelGene', to='main.Gene'),
        ),
        migrations.AlterField(
            model_name='panelgene',
            name='transcript',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrefferedTranscript', to='main.Transcript'),
        ),
    ]
