# Generated by Django 3.0.4 on 2020-03-11 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200311_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelgene',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrefferedTranscript', to='main.Transcript'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='GeneKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_key', models.CharField(max_length=10, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gene_keys', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('genes', models.ManyToManyField(related_name='gene_keys', to='main.Gene')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GeneKey', to='main.Panel')),
            ],
        ),
    ]
