# Generated by Django 3.0.4 on 2020-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200314_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='genekey',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
