# Generated by Django 3.0.4 on 2020-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_genekey_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genekey',
            name='comment',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
