# Generated by Django 3.0.4 on 2020-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200315_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genekey',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
