# Generated by Django 3.0.4 on 2020-04-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20200407_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to=settings.AUTH_USER_MODEL),
        ),
    ]
