# Generated by Django 3.0.4 on 2020-04-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200407_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genekey',
            old_name='gene_key',
            new_name='key',
        ),
    ]
