# Generated by Django 3.0.4 on 2020-04-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200407_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelgene',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PanelGene', to='main.Gene'),
        ),
        migrations.AlterField(
            model_name='panelgene',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PanelGene', to='main.Panel'),
        ),
        migrations.AlterField(
            model_name='panelgene',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PrefferedTranscript', to='main.Transcript'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='main.Gene'),
        ),
    ]
