# Generated by Django 3.0.4 on 2020-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200408_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='use_by_default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
