# Generated by Django 3.0.4 on 2020-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200408_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='panelgene',
            unique_together={('panel', 'gene')},
        ),
    ]
